"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.int120 = exports.int112 = exports.int104 = exports.int96 = exports.int88 = exports.int80 = exports.int72 = exports.int64 = exports.int56 = exports.int48 = exports.int40 = exports.int32 = exports.int24 = exports.int16 = exports.int8 = exports.Uint = exports.uint256 = exports.uint248 = exports.uint240 = exports.uint232 = exports.uint224 = exports.uint216 = exports.uint208 = exports.uint200 = exports.uint192 = exports.uint184 = exports.uint176 = exports.uint168 = exports.uint160 = exports.uint152 = exports.uint144 = exports.uint136 = exports.uint128 = exports.uint120 = exports.uint112 = exports.uint104 = exports.uint96 = exports.uint88 = exports.uint80 = exports.uint72 = exports.uint64 = exports.uint56 = exports.uint48 = exports.uint40 = exports.uint32 = exports.uint24 = exports.uint16 = exports.uint8 = exports.BaseInteger = exports.type = void 0;
exports.unchecked = exports.Int = exports.int256 = exports.int248 = exports.int240 = exports.int232 = exports.int224 = exports.int216 = exports.int208 = exports.int200 = exports.int192 = exports.int184 = exports.int176 = exports.int168 = exports.int160 = exports.int152 = exports.int144 = exports.int136 = exports.int128 = void 0;
var type_1 = require("./numbers/type");
Object.defineProperty(exports, "type", { enumerable: true, get: function () { return type_1.type; } });
var base_1 = require("./numbers/base");
Object.defineProperty(exports, "BaseInteger", { enumerable: true, get: function () { return base_1.BaseInteger; } });
var uint_1 = require("./numbers/uint");
Object.defineProperty(exports, "uint8", { enumerable: true, get: function () { return uint_1.uint8; } });
Object.defineProperty(exports, "uint16", { enumerable: true, get: function () { return uint_1.uint16; } });
Object.defineProperty(exports, "uint24", { enumerable: true, get: function () { return uint_1.uint24; } });
Object.defineProperty(exports, "uint32", { enumerable: true, get: function () { return uint_1.uint32; } });
Object.defineProperty(exports, "uint40", { enumerable: true, get: function () { return uint_1.uint40; } });
Object.defineProperty(exports, "uint48", { enumerable: true, get: function () { return uint_1.uint48; } });
Object.defineProperty(exports, "uint56", { enumerable: true, get: function () { return uint_1.uint56; } });
Object.defineProperty(exports, "uint64", { enumerable: true, get: function () { return uint_1.uint64; } });
Object.defineProperty(exports, "uint72", { enumerable: true, get: function () { return uint_1.uint72; } });
Object.defineProperty(exports, "uint80", { enumerable: true, get: function () { return uint_1.uint80; } });
Object.defineProperty(exports, "uint88", { enumerable: true, get: function () { return uint_1.uint88; } });
Object.defineProperty(exports, "uint96", { enumerable: true, get: function () { return uint_1.uint96; } });
Object.defineProperty(exports, "uint104", { enumerable: true, get: function () { return uint_1.uint104; } });
Object.defineProperty(exports, "uint112", { enumerable: true, get: function () { return uint_1.uint112; } });
Object.defineProperty(exports, "uint120", { enumerable: true, get: function () { return uint_1.uint120; } });
Object.defineProperty(exports, "uint128", { enumerable: true, get: function () { return uint_1.uint128; } });
Object.defineProperty(exports, "uint136", { enumerable: true, get: function () { return uint_1.uint136; } });
Object.defineProperty(exports, "uint144", { enumerable: true, get: function () { return uint_1.uint144; } });
Object.defineProperty(exports, "uint152", { enumerable: true, get: function () { return uint_1.uint152; } });
Object.defineProperty(exports, "uint160", { enumerable: true, get: function () { return uint_1.uint160; } });
Object.defineProperty(exports, "uint168", { enumerable: true, get: function () { return uint_1.uint168; } });
Object.defineProperty(exports, "uint176", { enumerable: true, get: function () { return uint_1.uint176; } });
Object.defineProperty(exports, "uint184", { enumerable: true, get: function () { return uint_1.uint184; } });
Object.defineProperty(exports, "uint192", { enumerable: true, get: function () { return uint_1.uint192; } });
Object.defineProperty(exports, "uint200", { enumerable: true, get: function () { return uint_1.uint200; } });
Object.defineProperty(exports, "uint208", { enumerable: true, get: function () { return uint_1.uint208; } });
Object.defineProperty(exports, "uint216", { enumerable: true, get: function () { return uint_1.uint216; } });
Object.defineProperty(exports, "uint224", { enumerable: true, get: function () { return uint_1.uint224; } });
Object.defineProperty(exports, "uint232", { enumerable: true, get: function () { return uint_1.uint232; } });
Object.defineProperty(exports, "uint240", { enumerable: true, get: function () { return uint_1.uint240; } });
Object.defineProperty(exports, "uint248", { enumerable: true, get: function () { return uint_1.uint248; } });
Object.defineProperty(exports, "uint256", { enumerable: true, get: function () { return uint_1.uint256; } });
Object.defineProperty(exports, "Uint", { enumerable: true, get: function () { return uint_1.Uint; } });
var int_1 = require("./numbers/int");
Object.defineProperty(exports, "int8", { enumerable: true, get: function () { return int_1.int8; } });
Object.defineProperty(exports, "int16", { enumerable: true, get: function () { return int_1.int16; } });
Object.defineProperty(exports, "int24", { enumerable: true, get: function () { return int_1.int24; } });
Object.defineProperty(exports, "int32", { enumerable: true, get: function () { return int_1.int32; } });
Object.defineProperty(exports, "int40", { enumerable: true, get: function () { return int_1.int40; } });
Object.defineProperty(exports, "int48", { enumerable: true, get: function () { return int_1.int48; } });
Object.defineProperty(exports, "int56", { enumerable: true, get: function () { return int_1.int56; } });
Object.defineProperty(exports, "int64", { enumerable: true, get: function () { return int_1.int64; } });
Object.defineProperty(exports, "int72", { enumerable: true, get: function () { return int_1.int72; } });
Object.defineProperty(exports, "int80", { enumerable: true, get: function () { return int_1.int80; } });
Object.defineProperty(exports, "int88", { enumerable: true, get: function () { return int_1.int88; } });
Object.defineProperty(exports, "int96", { enumerable: true, get: function () { return int_1.int96; } });
Object.defineProperty(exports, "int104", { enumerable: true, get: function () { return int_1.int104; } });
Object.defineProperty(exports, "int112", { enumerable: true, get: function () { return int_1.int112; } });
Object.defineProperty(exports, "int120", { enumerable: true, get: function () { return int_1.int120; } });
Object.defineProperty(exports, "int128", { enumerable: true, get: function () { return int_1.int128; } });
Object.defineProperty(exports, "int136", { enumerable: true, get: function () { return int_1.int136; } });
Object.defineProperty(exports, "int144", { enumerable: true, get: function () { return int_1.int144; } });
Object.defineProperty(exports, "int152", { enumerable: true, get: function () { return int_1.int152; } });
Object.defineProperty(exports, "int160", { enumerable: true, get: function () { return int_1.int160; } });
Object.defineProperty(exports, "int168", { enumerable: true, get: function () { return int_1.int168; } });
Object.defineProperty(exports, "int176", { enumerable: true, get: function () { return int_1.int176; } });
Object.defineProperty(exports, "int184", { enumerable: true, get: function () { return int_1.int184; } });
Object.defineProperty(exports, "int192", { enumerable: true, get: function () { return int_1.int192; } });
Object.defineProperty(exports, "int200", { enumerable: true, get: function () { return int_1.int200; } });
Object.defineProperty(exports, "int208", { enumerable: true, get: function () { return int_1.int208; } });
Object.defineProperty(exports, "int216", { enumerable: true, get: function () { return int_1.int216; } });
Object.defineProperty(exports, "int224", { enumerable: true, get: function () { return int_1.int224; } });
Object.defineProperty(exports, "int232", { enumerable: true, get: function () { return int_1.int232; } });
Object.defineProperty(exports, "int240", { enumerable: true, get: function () { return int_1.int240; } });
Object.defineProperty(exports, "int248", { enumerable: true, get: function () { return int_1.int248; } });
Object.defineProperty(exports, "int256", { enumerable: true, get: function () { return int_1.int256; } });
Object.defineProperty(exports, "Int", { enumerable: true, get: function () { return int_1.Int; } });
var unchecked_1 = require("./unchecked");
Object.defineProperty(exports, "unchecked", { enumerable: true, get: function () { return unchecked_1.unchecked; } });
